# Tensor Basics

Please import `numpy` as np and also `torch`

In [1]:
import torch

In [2]:
torch.__version__

'2.4.1+cpu'

In [3]:
import numpy as np

Confirm you're using PyTorch version 1.1.0 using this command => `torch.__version__`

## Converting NumPy arrays to PyTorch tensors
A <a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.Tensor</tt></strong></a> is a multi-dimensional matrix containing elements of a single data type.<br>
Calculations between tensors can only happen if the tensors share the same dtype.<br>
In some cases tensors are used as a replacement for NumPy to use the power of GPUs (more on this later).

Create this array `[1,2,3,4,5]`, name it `arr`, print it, print dtype (`arr.dtype`), and also print the type of array (`type(arr)`)

In [4]:
arr = np.array([1, 2, 3, 4, 5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int32')

In [7]:
(type(arr))

numpy.ndarray

Use this code to have x in tensor format `x = torch.from_numpy(arr)`
<br> print x

In [8]:
x = torch.from_numpy(arr)

In [9]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

Print the type of data held by the tensor

In [10]:
type(x)

torch.Tensor

Print the tensor object type by both `print(type(x))` and `print(x.type())`

In [11]:
print(type(x))

<class 'torch.Tensor'>


In [12]:
print(x.type())

torch.IntTensor


Create `arr2` by `arr2 = np.arange(0.,12.).reshape(4,3)` and then print it in one Code Cell

In [13]:
arr2 = np.arange(0., 12.).reshape(4, 3)

In [14]:
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

Now convert this 2d array to Tensor (`x2`) using the command you learned earlier, and print it

In [15]:
x2 = torch.from_numpy(arr2)

In [16]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

Print the type of data held by the tensor `x2`

In [17]:
type(x2)

torch.Tensor

In [18]:
x2.type()

'torch.DoubleTensor'

Here <tt>torch.DoubleTensor</tt> refers to 64-bit floating point data.

<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
You can click on `Tensor Datatypes` title to direct you to their webpage

<br>
<br>

<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

## Copying vs. sharing

<a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from_numpy()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_tensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor()</tt></strong></a><br>

There are a number of different functions available for <a href='https://pytorch.org/docs/stable/torch.html#creation-ops'>creating tensors</a>. When using <a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from_numpy()</tt></strong></a> and <a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_tensor()</tt></strong></a>, the PyTorch tensor and the source NumPy array share the same memory. This means that changes to one affect the other. However, the <a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor()</tt></strong></a> function always makes a copy.

Create this array `arr = [0, 1, 2, 3, 4]` using `arange` function, then use `torch.from_numpy()` to create `t_arr`, and then print `t_arr`

In [19]:
arr = np.arange(0,5)

In [20]:
arr

array([0, 1, 2, 3, 4])

In [21]:
t_arr = torch.from_numpy(arr)

In [22]:
t_arr

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

Now uptdate the value of the third element in `arr` that is (2) to be (77)

In [23]:
arr[2] = 77

In [24]:
arr

array([ 0,  1, 77,  3,  4])

Now print t_arr. What do you notice?

In [25]:
t_arr

tensor([ 0,  1, 77,  3,  4], dtype=torch.int32)

Now, use `torch.tensor()` and create `t_arr_new` using `arr`, and print it

In [26]:
t_arr_new = torch.tensor(arr)

In [27]:
t_arr_new

tensor([ 0,  1, 77,  3,  4], dtype=torch.int32)

Please go ahead and make a change to one of `arr`'s elements and check whether t_arr_new also changes
Type in the result here : _____

In [28]:
arr[2] = 2

In [29]:
arr

array([0, 1, 2, 3, 4])

In [30]:
t_arr_new

tensor([ 0,  1, 77,  3,  4], dtype=torch.int32)

In [31]:
# No CHange, because now it doesn't reference

## Class constructors
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.Tensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.FloatTensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.LongTensor()</tt></strong></a>, etc.<br>

There's a subtle difference between using the factory function <font color=black><tt>torch.tensor(data)</tt></font> and the class constructor <font color=black><tt>torch.Tensor(data)</tt></font>.<br>
The factory function determines the dtype from the incoming data, or from a passed-in dtype argument.<br>
The class constructor <tt>torch.Tensor()</tt>is simply an alias for <tt>torch.FloatTensor(data)</tt>. Consider the following:

Create a new array with the name of `data` using `numpy` library and `array` function to generate `array([1, 2, 3])`

In [32]:
data = np.array([1, 2, 3])

Now run this code => 
<br>`a = torch.Tensor(data)`
<br>`print(a, a.type())`
<br>
<br> Also pay attention that `torch.Tensor` function does the same thing as `torch.FloatTensor`

In [33]:
a = torch.Tensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


Now run this code => 
<br>`b = torch.tensor(data)`
<br>`print(b, b.type())`

In [34]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3], dtype=torch.int32) torch.IntTensor


Also run this code => 
<br>`c = torch.tensor(data, dtype=torch.long)`
<br> `print(c, c.type())`

In [35]:
c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3]) torch.LongTensor


### Creating tensors from scratch
#### Uninitialized tensors with <tt>.empty()</tt>
<a href='https://pytorch.org/docs/stable/torch.html#torch.empty'><strong><tt>torch.empty()</tt></strong></a> returns an <em>uninitialized</em> tensor. Essentially a block of memory is allocated according to the size of the tensor, and any values already sitting in the block are returned. This is similar to the behavior of <tt>numpy.empty()</tt>.

use `empty` function in `torch` library to create a 4 by 3 tensor and name it `x`

In [36]:
x = torch.empty(4, 3)

In [37]:
x

tensor([[-1.3329e-26,  1.3537e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

### Initialized tensors with <tt>.zeros()</tt> and <tt>.ones()</tt>
<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros'><strong><tt>torch.zeros(size)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones'><strong><tt>torch.ones(size)</tt></strong></a><br>

Create a 4 by 3 tensor of ones using `torch` library and show the data-type

In [38]:
y = torch.ones(4,3)

In [39]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
x.type()

'torch.FloatTensor'

It's a good idea to pass in the intended dtype. add dtype like this `dtype=torch.int64`, and crease a new X2, print it and show data-type

### Tensors from ranges
<a href='https://pytorch.org/docs/stable/torch.html#torch.arange'><strong><tt>torch.arange(start,end,step)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.linspace'><strong><tt>torch.linspace(start,end,steps)</tt></strong></a><br>
Note that with <tt>.arange()</tt>, <tt>end</tt> is exclusive, while with <tt>linspace()</tt>, <tt>end</tt> is inclusive.

Use `arange` function in `torch` library to create the following matrix. You can do this in one line of code by using `reshape`. In the same Code cell print it to confirm you got it right.
<br>tensor([[ 0,  2,  4],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       [ 6,  8, 10],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       [12, 14, 16]])

In [41]:
a = torch.arange(0, 18, 2).reshape(3, 3)
print(a)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


Now, use `linespace` and `reshape` to create this matrix

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ 6.5455,  8.1818,  9.8182, 11.4545],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[13.0909, 14.7273, 16.3636, 18.0000]])

In [42]:
b = torch.linspace(0, 18, 12).reshape(3, 4)
print(b)


tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


### Tensors from data
<tt>torch.tensor()</tt> will choose the dtype based on incoming data:

In [43]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


Alternatively you can set the type by the tensor method used.
For a list of tensor types visit https://pytorch.org/docs/stable/tensors.html

In [44]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


You can also pass the dtype in as an argument. For a list of dtypes visit https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype<br>

In [45]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


### Changing the dtype of existing tensors
Don't be tempted to use <tt>x = torch.tensor(x, dtype=torch.type)</tt> as it will raise an error about improper use of tensor cloning.<br>
Instead, use the tensor <tt>.type()</tt> method.

In [46]:
print('Old:', x.type())
x = x.type(torch.int64)
print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


### Random number tensors
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand'><strong><tt>torch.rand(size)</tt></strong></a> returns random samples from a uniform distribution over [0, 1)<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn'><strong><tt>torch.randn(size)</tt></strong></a> returns samples from the "standard normal" distribution [σ = 1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;Unlike <tt>rand</tt> which is uniform, values closer to zero are more likely to appear.<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint'><strong><tt>torch.randint(low,high,size)</tt></strong></a> returns random integers from low (inclusive) to high (exclusive)

Create a random 4*3 matrix (`xx1`) using `rand` in `torch` library and then print it

In [47]:
xx1 = torch.rand(4, 3)
print(xx1)

tensor([[0.2352, 0.4409, 0.9873],
        [0.8292, 0.2971, 0.0863],
        [0.6124, 0.0254, 0.5398],
        [0.9336, 0.8147, 0.7027]])


Now, use `randn` function to create `xx2` and print it.

In [48]:
xx2 = torch.randn(4, 3)
print(xx2)

tensor([[ 0.6182,  0.4079,  0.2912],
        [-1.3445, -0.0074, -0.3014],
        [-0.1058, -0.5455,  0.9880],
        [-0.7816, -0.8447,  1.4492]])


Use `randint` function to create `xx3` and print it.

In [49]:
xx3 = torch.randint(0, 10, (4, 3))
print(xx3)

tensor([[7, 5, 2],
        [0, 4, 5],
        [0, 3, 9],
        [0, 8, 9]])


### Random number tensors that follow the input size
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand_like'><strong><tt>torch.rand_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn_like'><strong><tt>torch.randn_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint_like'><strong><tt>torch.randint_like(input,low,high)</tt></strong></a><br> these return random number tensors with the same size as <tt>input</tt>

In [50]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [51]:
x2 = torch.randn_like(x)
print(x2)

tensor([[ 0.2537, -1.4871,  1.5832, -0.6048, -0.1057],
        [ 0.9842,  0.2620, -0.9205,  0.5841,  0.2687]])


The same syntax can be used with<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros_like'><strong><tt>torch.zeros_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones_like'><strong><tt>torch.ones_like(input)</tt></strong></a>

In [52]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [59]:
x = torch.zeros(2, 5)
print(x)
x2 = torch.randn_like(x)
print(x2)

x3 = torch.ones_like(x2)
print(x3)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 1.1561,  0.3965, -2.4661,  0.3623,  0.3765],
        [-0.1808,  0.3930,  0.4327, -1.3627,  1.3564]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


### Setting the random seed
<a href='https://pytorch.org/docs/stable/torch.html#torch.manual_seed'><strong><tt>torch.manual_seed(int)</tt></strong></a> is used to obtain reproducible results

In [60]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [61]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


## Tensor attributes
Besides <tt>dtype</tt>, we can look at other <a href='https://pytorch.org/docs/stable/tensor_attributes.html'>tensor attributes</a> like <tt>shape</tt>, <tt>device</tt> and <tt>layout</tt>

In [62]:
x.shape

torch.Size([2, 3])

In [63]:
x.size()  # equivalent to x.shape

torch.Size([2, 3])

In [64]:
x.device

device(type='cpu')

PyTorch supports use of multiple <a href='https://pytorch.org/docs/stable/tensor_attributes.html#torch-device'>devices</a>, harnessing the power of one or more GPUs in addition to the CPU. We won't explore that here, but you should know that operations between tensors can only happen for tensors installed on the same device.

In [65]:
x.layout

torch.strided

PyTorch has a class to hold the <a href='https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.layout'>memory layout</a> option. The default setting of <a href='https://en.wikipedia.org/wiki/Stride_of_an_array'>strided</a> will suit our purposes throughout the course.

## Indexing and slicing
Extracting specific values from a tensor works just the same as with NumPy arrays<br>
<figure>
   <img src="./images/numpy_indexing.PNG"  alt='missing' width="400"  >
<figure/>

Create this 2d tensor using `arange` and `reshape` as 'x' and print it.
<br> tensor([[0, 1],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [2, 3],
 <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [4, 5]])

In [66]:
x = torch.arange(6).reshape(3, 2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


Grab the right hand column values and show this
<br>tensor([1, 3, 5])

Grab the right hand column as a (3,1) slice and show this
<br> tensor([[1],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [3],
 <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [5]])

In [67]:
right_col = x[:, 1]
print(right_col)

tensor([1, 3, 5])


In [68]:
right_col_slice = x[:, 1].reshape(3, 1)
print(right_col_slice)

tensor([[1],
        [3],
        [5]])


### Reshape tensors with <tt>.view()</tt>
<a href='https://pytorch.org/docs/master/tensors.html#torch.Tensor.view'><strong><tt>view()</tt></strong></a> and <a href='https://pytorch.org/docs/master/torch.html#torch.reshape'><strong><tt>reshape()</tt></strong></a> do essentially the same thing by returning a reshaped tensor without changing the original tensor in place.<br>
There's a good discussion of the differences <a href='https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch'>here</a>.

Create an 1d tensor with 10 elements and name it `x3`

In [69]:
x3 = torch.arange(10)
print(x3.view(2, 5))
print(x3.view(5, 2))
print(x3)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Run this `x3.view(2,5)`

In [72]:
z = x3.view(2, 5)
x3[0] = 234
print(z)


tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


Now run this x.view(5,2)

In [73]:
z = x3.view(5, 2)
x3[0] = 234
print(z)

tensor([[234,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])


Prove x is unchanged by printing it

In [74]:
print(x3.view(2, -1))
print(x3.view(-1, 5))

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])
tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


### Views reflect the most current data

Type in this code =>

z = x.view(2,5)
<br>x[0]=234
<br>print(z)

In [75]:
z = x.view(2,5)
x[0]=234
print(z)

RuntimeError: shape '[2, 5]' is invalid for input of size 6

### Views can infer the correct size
By passing in <tt>-1</tt> PyTorch will infer the correct value from the given tensor

Run this => `x.view(2,-1)`, what do you expect?

In [76]:
x.view(2,-1)

tensor([[0, 1, 2],
        [3, 4, 5]])

Run this => `x.view(-1,5)`, what do you expect?

In [77]:
x.view(-1,5)

RuntimeError: shape '[-1, 5]' is invalid for input of size 6

### Tensor Arithmetic
Adding tensors can be performed a few different ways depending on the desired result.<br>

As a simple expression:
<br>`a = torch.tensor([1,2,3], dtype=torch.float)`
<br>`b = torch.tensor([4,5,6], dtype=torch.float)`
<br>`print(a + b)`

In [78]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([5., 7., 9.])


As arguments passed into a torch operation like this `print(torch.add(a, b))`

In [79]:
print(torch.add(a, b))

tensor([5., 7., 9.])


With an output tensor passed in as an argument:
<br>`result = torch.empty(3)`
<br>`torch.add(a, b, out=result)`  => Pay attention that this is equivalent to result=torch.add(a,b)
<br>`print(result)`

In [80]:
result = torch.empty(3)
torch.add(a, b, out=result)
print(result)

tensor([5., 7., 9.])


Changing a tensor in-place - run this code `a.add_(b)`, it is equivalent to a=torch.add(a,b). Then, print the new `a`


In [81]:
a.add_(b)
a

tensor([5., 7., 9.])

<div class="alert alert-info"><strong>NOTE:</strong> Any operation that changes a tensor in-place is post-fixed with an underscore _.
    <br>In the above example: <tt>a.add_(b)</tt> changed <tt>a</tt>.</div>

### Basic Tensor Operations
<table style="display: inline-block">
<caption style="text-align: center"><strong>Arithmetic</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>a + b</td><td>a.add(b)</td><td>element wise addition</td></tr>
<tr><td>a - b</td><td>a.sub(b)</td><td>subtraction</td></tr>
<tr><td>a * b</td><td>a.mul(b)</td><td>multiplication</td></tr>
<tr><td>a / b</td><td>a.div(b)</td><td>division</td></tr>
<tr><td>a % b</td><td>a.fmod(b)</td><td>modulo (remainder after division)</td></tr>
<tr><td>a<sup>b</sup></td><td>a.pow(b)</td><td>power</td></tr>
<tr><td>&nbsp;</td><td></td><td></td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Monomial Operations</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>|a|</td><td>torch.abs(a)</td><td>absolute value</td></tr>
<tr><td>1/a</td><td>torch.reciprocal(a)</td><td>reciprocal</td></tr>
<tr><td>$\sqrt{a}$</td><td>torch.sqrt(a)</td><td>square root</td></tr>
<tr><td>log(a)</td><td>torch.log(a)</td><td>natural log</td></tr>
<tr><td>e<sup>a</sup></td><td>torch.exp(a)</td><td>exponential</td></tr>
<tr><td>12.34  ==>  12.</td><td>torch.trunc(a)</td><td>truncated integer</td></tr>
<tr><td>12.34  ==>  0.34</td><td>torch.frac(a)</td><td>fractional component</td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Trigonometry</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>sin(a)</td><td>torch.sin(a)</td><td>sine</td></tr>
<tr><td>cos(a)</td><td>torch.sin(a)</td><td>cosine</td></tr>
<tr><td>tan(a)</td><td>torch.sin(a)</td><td>tangent</td></tr>
<tr><td>arcsin(a)</td><td>torch.asin(a)</td><td>arc sine</td></tr>
<tr><td>arccos(a)</td><td>torch.acos(a)</td><td>arc cosine</td></tr>
<tr><td>arctan(a)</td><td>torch.atan(a)</td><td>arc tangent</td></tr>
<tr><td>sinh(a)</td><td>torch.sinh(a)</td><td>hyperbolic sine</td></tr>
<tr><td>cosh(a)</td><td>torch.cosh(a)</td><td>hyperbolic cosine</td></tr>
<tr><td>tanh(a)</td><td>torch.tanh(a)</td><td>hyperbolic tangent</td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Summary Statistics</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>$\sum a$</td><td>torch.sum(a)</td><td>sum</td></tr>
<tr><td>$\bar a$</td><td>torch.mean(a)</td><td>mean</td></tr>
<tr><td>a<sub>max</sub></td><td>torch.max(a)</td><td>maximum</td></tr>
<tr><td>a<sub>min</sub></td><td>torch.min(a)</td><td>minimum</td></tr>
<tr><td colspan="3">torch.max(a,b) returns a tensor of size a<br>containing the element wise max between a and b</td></tr>
</table>

<div class="alert alert-info"><strong>NOTE:</strong> Most arithmetic operations require float values. Those that do work with integers return integer tensors.<br>
For example, <tt>torch.div(a,b)</tt> performs floor division (truncates the decimal) for integer types, and classic division for floats.</div>

#### Use the space below to experiment with different operations

Create two array `a` and `b` with the `dtype` to be `torch.float`, and then `print(torch.add(a,b).sum())`

In [82]:
a = torch.tensor([1, 2, 3], dtype=torch.float)
b = torch.tensor([4, 5, 6], dtype=torch.float)

# Addition
print(a + b)
print(torch.add(a, b).sum())

# In-place addition
a.add_(b)
print(a)


tensor([5., 7., 9.])
tensor(21.)
tensor([5., 7., 9.])


Carry out two other operations that you would like.

In [83]:
# Element-wise multiplication
print(a.mul(b))

tensor([20., 35., 54.])


In [84]:
# Dot product
print(a.dot(b))

tensor(109.)


## Dot products
A <a href='https://en.wikipedia.org/wiki/Dot_product'>dot product</a> is the sum of the products of the corresponding entries of two 1D tensors. If the tensors are both vectors, the dot product is given as:<br>

$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$

If the tensors include a column vector, then the dot product is the sum of the result of the multiplied matrices. For example:<br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>
Dot products can be expressed as <a href='https://pytorch.org/docs/stable/torch.html#torch.dot'><strong><tt>torch.dot(a,b)</tt></strong></a> or `a.dot(b)` or `b.dot(a)`

Create two `float` `1D tensor` with namse `aa`and `bb`

In [85]:
aa = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float)
bb = torch.tensor([4.0, 5.0, 6.0], dtype=torch.float)

Now do these two operations and compare
<br> `print(a.mul(b))`
<br> `print(a.dot(b))`

In [86]:
# Element-wise multiplication
element_wise_mul = a.mul(b)

# Dot product
dot_product = a.dot(b)

# Print the results
print("Element-wise multiplication:", element_wise_mul)
print("Dot product:", dot_product)

Element-wise multiplication: tensor([20., 35., 54.])
Dot product: tensor(109.)


<div class="alert alert-info"><strong>NOTE:</strong> There's a slight difference between <tt>torch.dot()</tt> and <tt>numpy.dot()</tt>. While <tt>torch.dot()</tt> only accepts 1D arguments and returns a dot product, <tt>numpy.dot()</tt> also accepts 2D arguments and performs matrix multiplication. We show matrix multiplication below.</div>

## Matrix multiplication
2D <a href='https://en.wikipedia.org/wiki/Matrix_multiplication'>Matrix multiplication</a> is possible when the number of columns in tensor <strong><tt>A</tt></strong> matches the number of rows in tensor <strong><tt>B</tt></strong>. In this case, the product of tensor <strong><tt>A</tt></strong> with size $(x,y)$ and tensor <strong><tt>B</tt></strong> with size $(y,z)$ results in a tensor of size $(x,z)$
<div>

$\begin{bmatrix} a & b & c \\
d & e & f \end{bmatrix} \;\times\; \begin{bmatrix} m & n \\ p & q \\ r & s \end{bmatrix} = \begin{bmatrix} (am+bp+cr) & (an+bq+cs) \\
(dm+ep+fr) & (dn+eq+fs) \end{bmatrix}$</div></div>

<div style="clear:both">Image source: <a href='https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg'>https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg</a></div>

Matrix multiplication can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.mm'><strong><tt>torch.mm(a,b)</tt></strong></a> or `a.mm(b)` or `a @ b`

create two `2d tensor` and the `dtype` should be `float`
<br>2d_a = [[0,2,4],[1,3,5]]
<br>2d_b = [[6,7],[8,9],[10,11]]



In [89]:
# Create two 2D float tensors
a = torch.tensor([[0.0, 2.0, 4.0], [1.0, 3.0, 5.0]])
b = torch.tensor([[6.0, 7.0], [8.0, 9.0], [10.0, 11.0]])

Now run the following codes =>
<br> `print('a: ',a.size())`
<br>`print('b: ',b.size())`
<br> `print('a x b: ',torch.mm(a,b).size())`

In [90]:
print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


Run these => `print(torch.mm(a,b))`, `print(a.mm(b))`, and `print(a @ b)`

In [91]:
print(torch.mm(a,b))

tensor([[56., 62.],
        [80., 89.]])


In [92]:
print(a.mm(b))

tensor([[56., 62.],
        [80., 89.]])


In [93]:
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])


### Matrix multiplication with broadcasting
Matrix multiplication that involves <a href='https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics'>broadcasting</a> can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.matmul'><strong><tt>torch.matmul(a,b)</tt></strong></a> or `a.matmul(b)` or `a @ b`

ok, create a 2*3*4 `randn` tensor and name it `t1`
create a 4*5 `randn` tensor and name it `t2`

In [94]:
# Create random tensors
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

In [95]:
t1

tensor([[[-0.0431, -1.6047,  1.7878, -0.4780],
         [-0.2429, -0.9342, -0.2483, -1.2082],
         [-2.3169, -0.2168, -1.3847, -0.8712]],

        [[-0.2234,  1.7174,  0.3189, -0.4245],
         [-0.8286,  0.3309, -1.5576,  0.9956],
         [-0.8798, -0.6011, -1.2742,  2.1228]]])

In [96]:
t2

tensor([[-1.0892, -0.3553, -0.9138, -0.6581,  2.2181],
        [ 0.5232,  0.3466, -0.1973, -1.0546,  1.2780],
        [ 0.1453,  0.2311,  0.0566,  0.4263,  0.5750],
        [-0.6417, -2.2064, -0.7508,  2.8140,  0.3598]])

Run this to make sure about the size => `print(torch.matmul(t1, t2).size())`

In [97]:
print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


However, the same operation raises a RuntimeError with torch.mm():  => `print(torch.mm(t1, t2).size())`

In [98]:
print(torch.mm(t1, t2).size())

RuntimeError: self must be a matrix

## L2 or Euclidian Norm
See <a href='https://pytorch.org/docs/stable/torch.html#torch.norm'><strong><tt>torch.norm()</tt></strong></a>

The <a href='https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm'>Euclidian Norm</a> gives the vector norm of $x$ where $x=(x_1,x_2,...,x_n)$.<br>
It is calculated as<br>

${\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}:={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}}$


When applied to a matrix, <tt>torch.norm()</tt> returns the <a href='https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm'>Frobenius norm</a> by default.

Calculate the norm of this tensor `s=[2.,5.,8.,14.]` using `s.norm()`

In [99]:
s = torch.tensor([2., 5., 8., 14.])

In [101]:
l2_norm = s.norm()
print("L2 Norm of s:", l2_norm.item())

L2 Norm of s: 17.0


In [102]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [103]:
t1 = torch.tensor([2., 5., 8., 14.])
t2 = torch.tensor([1., 4., 7., 13.])

In [104]:
mse_value = mse(t1, t2)
print("Mean Squared Error between t1 and t2:", mse_value.item())

Mean Squared Error between t1 and t2: 1.0


This can be useful in certain calculations like Mean Squared Error:<br>
<tt>
def mse(t1, t2):<br>
&nbsp;&nbsp;&nbsp;&nbsp;diff = t1 - t2<br>
    &nbsp;&nbsp;&nbsp;&nbsp;return torch.sum(diff * diff) / diff<strong>.numel()</strong></tt>